// <auto-generated />
namespace FYPPharmAssistant.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Addingsalesmodule : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addingsalesmodule));
        
        string IMigrationMetadata.Id
        {
            get { return "201509180746358_Adding sales module"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
